---
deployment:
  tasks:
    # 1. Exact paths for user: national
    - export FRONTEND_PATH=/home/national/sklove.nit.bd
    - export BACKEND_PATH=/home/national/api.sklove.nit.bd

    # 2. Deploy Frontend Files to sklove.nit.bd
    - /bin/cp -R dist/* $FRONTEND_PATH/
    - /bin/cp public/.htaccess $FRONTEND_PATH/.htaccess

    # 3. Deploy Laravel Backend API to api.sklove.nit.bd
    - /bin/cp -R laravel-api/laravel-api/* $BACKEND_PATH/
